swagger: "2.0"
info:
  description: "Contains all available API endpoints in this codebase"
  version: "1.0.0"
  title: "Argent Bank"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "franz.mongin@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:3001"
basePath: "/api/v1"
tags:
- name: "transactions"
  description: ""
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
schemes:
- "https"
- "http"
paths:
  /transactions:
    get:
      security:
        - Bearer: []
      tags:
      - "transactions"
      summary: "User transactions API"
      description: "Get all transactions from current month from a given user"
      produces:
      - "application/json"
      parameters:
        - in: "header"
          name: "Authorization"
          description: ""
          required: true
          type: "string"
        - in: "query"
          name: "month"
          type: "string"
          description: "the concerned month"
      responses:
        '200':
          description: User transactions retrieved successfully
          schema:
            $ref: '#/definitions/TransactionsResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /transaction/{id}:
    get:
      security:
        - Bearer: []
      tags:
      - "transaction"
      summary: "User transaction API"
      description: "Get one transaction from a given user"
      produces:
      - "application/json"
      parameters:
        - in: "header"
          name: "Authorization"
          description: ""
          required: true
          type: "string"
        
        - in: "path"
          name: id
          type: integer
          required: true
          description: Numeric ID of the transaction
      responses:
        '200':
          description: User transaction retrieved successfully
          schema:
            $ref: '#/definitions/TransactionModel'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
      - "transaction"
      summary: "User transaction API"
      description: "Update one transaction from a given user"
      produces:
      - "application/json"
      parameters:
        - in: "header"
          name: "Authorization"
          description: ""
          required: true
          type: "string"
        
        - in: "path"
          name: id
          type: integer
          required: true
          description: Numeric ID of the transaction
        - in: "body"
          name: "transaction"
          description: the transaction to update
          schema:
            type: object
            properties:
              date:
                type: "string"
              amount:
                type: "number"
              description:
                type: "string"
              
              
      responses:
        '200':
          description: User transaction updated successfully
          schema:
            $ref: '#/definitions/TransactionModel'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    
  

securityDefinitions:
  Bearer:
    type: "apiKey"
    name: "Authorization"
    in: "header"
definitions:
  TransactionModel:
    type: "object"
    properties:
      id:
        type: "integer"
      userId:
        type: "integer"
      date:
        type: "string"
        
      amount:
        type: "number"
        
      description:
        type: "string"
  TransactionsResponse:
    type: "array"
    items:
      $ref: '#/definitions/TransactionModel'
    example:
        - id: 1
          userId: 24
          date: "2021-12-05"
          amount: 50.25
          description: "coucou"
        - id: 2
          userId: 34
          date: "2021-12-10"
          amount: 35.12
          description: "coucou"